/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_QtNetCoreQml_WRAP_H_
#define SWIG_QtNetCoreQml_WRAP_H_

class SwigDirector_NetTypeInfoCallbacks : public NetTypeInfoCallbacks, public Swig::Director {

public:
    SwigDirector_NetTypeInfoCallbacks();
    virtual ~SwigDirector_NetTypeInfoCallbacks();
    virtual bool isValidType(char *typeName);
    virtual NetInterTypeEnum GetNetInterType(char *typeName);
    virtual void BuildTypeInfo(NetTypeInfo *typeInfo);
    virtual void CreateInstance(NetTypeInfo *typeInfo, NetInstance *instance);
    virtual void ReadProperty(NetPropertyInfo *propertyInfo, NetInstance *target, NetInstance *result);
    virtual void WriteProperty(NetPropertyInfo *propertyInfo, NetInstance *target, NetInstance *value);
    virtual void InvokeMethod(NetMethodInfo *methodInfo, NetInstance *target, std::vector< NetInstance * > parameters, NetInstance *result);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(char *);
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)(char *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackisValidType, SWIG_Callback1_t callbackGetNetInterType, SWIG_Callback2_t callbackBuildTypeInfo, SWIG_Callback3_t callbackCreateInstance, SWIG_Callback4_t callbackReadProperty, SWIG_Callback5_t callbackWriteProperty, SWIG_Callback6_t callbackInvokeMethod);

private:
    SWIG_Callback0_t swig_callbackisValidType;
    SWIG_Callback1_t swig_callbackGetNetInterType;
    SWIG_Callback2_t swig_callbackBuildTypeInfo;
    SWIG_Callback3_t swig_callbackCreateInstance;
    SWIG_Callback4_t swig_callbackReadProperty;
    SWIG_Callback5_t swig_callbackWriteProperty;
    SWIG_Callback6_t swig_callbackInvokeMethod;
    void swig_init_callbacks();
};


#endif
