//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Qt.NetCore {

public class StringVector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<string>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StringVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StringVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~StringVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_StringVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public StringVector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (string element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public string this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(string[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(string[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, string[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<string> global::System.Collections.Generic.IEnumerable<string>.GetEnumerator() {
    return new StringVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new StringVectorEnumerator(this);
  }

  public StringVectorEnumerator GetEnumerator() {
    return new StringVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class StringVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<string>
  {
    private StringVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public StringVectorEnumerator(StringVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public string Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (string)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    QtNetCoreQmlPINVOKE.StringVector_Clear(swigCPtr);
  }

  public void Add(string x) {
    QtNetCoreQmlPINVOKE.StringVector_Add(swigCPtr, x);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = QtNetCoreQmlPINVOKE.StringVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = QtNetCoreQmlPINVOKE.StringVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    QtNetCoreQmlPINVOKE.StringVector_reserve(swigCPtr, n);
  }

  public StringVector() : this(QtNetCoreQmlPINVOKE.new_StringVector__SWIG_0(), true) {
  }

  public StringVector(StringVector other) : this(QtNetCoreQmlPINVOKE.new_StringVector__SWIG_1(StringVector.getCPtr(other)), true) {
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public StringVector(int capacity) : this(QtNetCoreQmlPINVOKE.new_StringVector__SWIG_2(capacity), true) {
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  private string getitemcopy(int index) {
    string ret = QtNetCoreQmlPINVOKE.StringVector_getitemcopy(swigCPtr, index);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private string getitem(int index) {
    string ret = QtNetCoreQmlPINVOKE.StringVector_getitem(swigCPtr, index);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, string val) {
    QtNetCoreQmlPINVOKE.StringVector_setitem(swigCPtr, index, val);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(StringVector values) {
    QtNetCoreQmlPINVOKE.StringVector_AddRange(swigCPtr, StringVector.getCPtr(values));
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public StringVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.StringVector_GetRange(swigCPtr, index, count);
    StringVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new StringVector(cPtr, true);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, string x) {
    QtNetCoreQmlPINVOKE.StringVector_Insert(swigCPtr, index, x);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, StringVector values) {
    QtNetCoreQmlPINVOKE.StringVector_InsertRange(swigCPtr, index, StringVector.getCPtr(values));
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    QtNetCoreQmlPINVOKE.StringVector_RemoveAt(swigCPtr, index);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    QtNetCoreQmlPINVOKE.StringVector_RemoveRange(swigCPtr, index, count);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public static StringVector Repeat(string value, int count) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.StringVector_Repeat(value, count);
    StringVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new StringVector(cPtr, true);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    QtNetCoreQmlPINVOKE.StringVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    QtNetCoreQmlPINVOKE.StringVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, StringVector values) {
    QtNetCoreQmlPINVOKE.StringVector_SetRange(swigCPtr, index, StringVector.getCPtr(values));
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(string value) {
    bool ret = QtNetCoreQmlPINVOKE.StringVector_Contains(swigCPtr, value);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int IndexOf(string value) {
    int ret = QtNetCoreQmlPINVOKE.StringVector_IndexOf(swigCPtr, value);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int LastIndexOf(string value) {
    int ret = QtNetCoreQmlPINVOKE.StringVector_LastIndexOf(swigCPtr, value);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Remove(string value) {
    bool ret = QtNetCoreQmlPINVOKE.StringVector_Remove(swigCPtr, value);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
namespace Qt.NetCore {

public enum NetVariantTypeEnum {
  NetVariantTypeEnum_Invalid,
  NetVariantTypeEnum_Bool,
  NetVariantTypeEnum_Int,
  NetVariantTypeEnum_Double,
  NetVariantTypeEnum_String,
  NetVariantTypeEnum_Date,
  NetVariantTypeEnum_Object
}

}
namespace Qt.NetCore {

public class NetInstance : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetInstance(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetInstance obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NetInstance() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_NetInstance(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public NetInstance(System.IntPtr gcHandle, NetTypeInfo typeInfo) : this(QtNetCoreQmlPINVOKE.new_NetInstance(gcHandle, NetTypeInfo.getCPtr(typeInfo)), true) {
  }

  public System.IntPtr GetGCHandle() { 
    System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetInstance_GetGCHandle(swigCPtr);
    return cPtr;
    }

  public NetTypeInfo GetTypeInfo() {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetInstance_GetTypeInfo(swigCPtr);
    NetTypeInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetTypeInfo(cPtr, false);
    return ret;
  }

}

}
namespace Qt.NetCore {

public class NetVariant : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetVariant(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetVariant obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NetVariant() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_NetVariant(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public NetVariant() : this(QtNetCoreQmlPINVOKE.new_NetVariant(), true) {
  }

  public NetVariantTypeEnum GetVariantType() {
    NetVariantTypeEnum ret = (NetVariantTypeEnum)QtNetCoreQmlPINVOKE.NetVariant_GetVariantType(swigCPtr);
    return ret;
  }

  public void SetNetInstance(NetInstance netInstance) {
    QtNetCoreQmlPINVOKE.NetVariant_SetNetInstance(swigCPtr, NetInstance.getCPtr(netInstance));
  }

  public NetInstance GetNetInstance() {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetVariant_GetNetInstance(swigCPtr);
    NetInstance ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetInstance(cPtr, false);
    return ret;
  }

  public void SetBool(bool value) {
    QtNetCoreQmlPINVOKE.NetVariant_SetBool(swigCPtr, value);
  }

  public bool GetBool() {
    bool ret = QtNetCoreQmlPINVOKE.NetVariant_GetBool(swigCPtr);
    return ret;
  }

  public void SetInt(int value) {
    QtNetCoreQmlPINVOKE.NetVariant_SetInt(swigCPtr, value);
  }

  public int GetInt() {
    int ret = QtNetCoreQmlPINVOKE.NetVariant_GetInt(swigCPtr);
    return ret;
  }

}

}
namespace Qt.NetCore {

public class NetTypeInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetTypeInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetTypeInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NetTypeInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_NetTypeInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public NetTypeInfo(string typeName) : this(QtNetCoreQmlPINVOKE.new_NetTypeInfo(typeName), true) {
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetTypeName() {
    string ret = QtNetCoreQmlPINVOKE.NetTypeInfo_GetTypeName(swigCPtr);
    return ret;
  }

  public void AddMethod(NetMethodInfo methodInfo) {
    QtNetCoreQmlPINVOKE.NetTypeInfo_AddMethod(swigCPtr, NetMethodInfo.getCPtr(methodInfo));
  }

  public int GetMethodCount() {
    int ret = QtNetCoreQmlPINVOKE.NetTypeInfo_GetMethodCount(swigCPtr);
    return ret;
  }

  public NetMethodInfo GetMethod(int index) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetTypeInfo_GetMethod(swigCPtr, index);
    NetMethodInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetMethodInfo(cPtr, false);
    return ret;
  }

  public void AddProperty(NetPropertyInfo propertyInfo) {
    QtNetCoreQmlPINVOKE.NetTypeInfo_AddProperty(swigCPtr, NetPropertyInfo.getCPtr(propertyInfo));
  }

  public int GetPropertyCount() {
    int ret = QtNetCoreQmlPINVOKE.NetTypeInfo_GetPropertyCount(swigCPtr);
    return ret;
  }

  public NetPropertyInfo GetProperty(int index) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetTypeInfo_GetProperty(swigCPtr, index);
    NetPropertyInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetPropertyInfo(cPtr, false);
    return ret;
  }

}

}
namespace Qt.NetCore {

public class NetMethodInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetMethodInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetMethodInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NetMethodInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_NetMethodInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public NetMethodInfo(NetTypeInfo parentTypeInfo, string methodName, NetTypeInfo returnType) : this(QtNetCoreQmlPINVOKE.new_NetMethodInfo(NetTypeInfo.getCPtr(parentTypeInfo), methodName, NetTypeInfo.getCPtr(returnType)), true) {
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetMethodName() {
    string ret = QtNetCoreQmlPINVOKE.NetMethodInfo_GetMethodName(swigCPtr);
    return ret;
  }

  public NetTypeInfo GetReturnType() {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetMethodInfo_GetReturnType(swigCPtr);
    NetTypeInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetTypeInfo(cPtr, false);
    return ret;
  }

  public void AddParameter(string parameterName, NetTypeInfo typeInfo) {
    QtNetCoreQmlPINVOKE.NetMethodInfo_AddParameter(swigCPtr, parameterName, NetTypeInfo.getCPtr(typeInfo));
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetParameterCount() {
    int ret = QtNetCoreQmlPINVOKE.NetMethodInfo_GetParameterCount(swigCPtr);
    return ret;
  }

  public void GetParameterInfo(int index, SWIGTYPE_p_std__string parameterName, SWIGTYPE_p_p_NetTypeInfo typeInfo) {
    QtNetCoreQmlPINVOKE.NetMethodInfo_GetParameterInfo(swigCPtr, index, SWIGTYPE_p_std__string.getCPtr(parameterName), SWIGTYPE_p_p_NetTypeInfo.getCPtr(typeInfo));
  }

}

}
namespace Qt.NetCore {

public class NetPropertyInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetPropertyInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetPropertyInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NetPropertyInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_NetPropertyInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public NetPropertyInfo(NetTypeInfo parentTypeInfo, string propertyName, NetTypeInfo returnType, bool canRead, bool canWrite) : this(QtNetCoreQmlPINVOKE.new_NetPropertyInfo(NetTypeInfo.getCPtr(parentTypeInfo), propertyName, NetTypeInfo.getCPtr(returnType), canRead, canWrite), true) {
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public NetTypeInfo GetParentType() {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetPropertyInfo_GetParentType(swigCPtr);
    NetTypeInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetTypeInfo(cPtr, false);
    return ret;
  }

  public string GetPropertyName() {
    string ret = QtNetCoreQmlPINVOKE.NetPropertyInfo_GetPropertyName(swigCPtr);
    return ret;
  }

  public NetTypeInfo GetReturnType() {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetPropertyInfo_GetReturnType(swigCPtr);
    NetTypeInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetTypeInfo(cPtr, false);
    return ret;
  }

  public bool CanRead() {
    bool ret = QtNetCoreQmlPINVOKE.NetPropertyInfo_CanRead(swigCPtr);
    return ret;
  }

  public bool CanWrite() {
    bool ret = QtNetCoreQmlPINVOKE.NetPropertyInfo_CanWrite(swigCPtr);
    return ret;
  }

}

}
namespace Qt.NetCore {

public class NetInstanceVector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<NetInstance>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetInstanceVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetInstanceVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NetInstanceVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_NetInstanceVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public NetInstanceVector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (NetInstance element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public NetInstance this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(NetInstance[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(NetInstance[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, NetInstance[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<NetInstance> global::System.Collections.Generic.IEnumerable<NetInstance>.GetEnumerator() {
    return new NetInstanceVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new NetInstanceVectorEnumerator(this);
  }

  public NetInstanceVectorEnumerator GetEnumerator() {
    return new NetInstanceVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class NetInstanceVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<NetInstance>
  {
    private NetInstanceVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public NetInstanceVectorEnumerator(NetInstanceVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public NetInstance Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (NetInstance)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    QtNetCoreQmlPINVOKE.NetInstanceVector_Clear(swigCPtr);
  }

  public void Add(NetInstance x) {
    QtNetCoreQmlPINVOKE.NetInstanceVector_Add(swigCPtr, NetInstance.getCPtr(x));
  }

  private uint size() {
    uint ret = QtNetCoreQmlPINVOKE.NetInstanceVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = QtNetCoreQmlPINVOKE.NetInstanceVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    QtNetCoreQmlPINVOKE.NetInstanceVector_reserve(swigCPtr, n);
  }

  public NetInstanceVector() : this(QtNetCoreQmlPINVOKE.new_NetInstanceVector__SWIG_0(), true) {
  }

  public NetInstanceVector(NetInstanceVector other) : this(QtNetCoreQmlPINVOKE.new_NetInstanceVector__SWIG_1(NetInstanceVector.getCPtr(other)), true) {
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public NetInstanceVector(int capacity) : this(QtNetCoreQmlPINVOKE.new_NetInstanceVector__SWIG_2(capacity), true) {
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  private NetInstance getitemcopy(int index) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetInstanceVector_getitemcopy(swigCPtr, index);
    NetInstance ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetInstance(cPtr, false);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private NetInstance getitem(int index) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetInstanceVector_getitem(swigCPtr, index);
    NetInstance ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetInstance(cPtr, false);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, NetInstance val) {
    QtNetCoreQmlPINVOKE.NetInstanceVector_setitem(swigCPtr, index, NetInstance.getCPtr(val));
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(NetInstanceVector values) {
    QtNetCoreQmlPINVOKE.NetInstanceVector_AddRange(swigCPtr, NetInstanceVector.getCPtr(values));
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public NetInstanceVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetInstanceVector_GetRange(swigCPtr, index, count);
    NetInstanceVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetInstanceVector(cPtr, true);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, NetInstance x) {
    QtNetCoreQmlPINVOKE.NetInstanceVector_Insert(swigCPtr, index, NetInstance.getCPtr(x));
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, NetInstanceVector values) {
    QtNetCoreQmlPINVOKE.NetInstanceVector_InsertRange(swigCPtr, index, NetInstanceVector.getCPtr(values));
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    QtNetCoreQmlPINVOKE.NetInstanceVector_RemoveAt(swigCPtr, index);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    QtNetCoreQmlPINVOKE.NetInstanceVector_RemoveRange(swigCPtr, index, count);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public static NetInstanceVector Repeat(NetInstance value, int count) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetInstanceVector_Repeat(NetInstance.getCPtr(value), count);
    NetInstanceVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetInstanceVector(cPtr, true);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    QtNetCoreQmlPINVOKE.NetInstanceVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    QtNetCoreQmlPINVOKE.NetInstanceVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, NetInstanceVector values) {
    QtNetCoreQmlPINVOKE.NetInstanceVector_SetRange(swigCPtr, index, NetInstanceVector.getCPtr(values));
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(NetInstance value) {
    bool ret = QtNetCoreQmlPINVOKE.NetInstanceVector_Contains(swigCPtr, NetInstance.getCPtr(value));
    return ret;
  }

  public int IndexOf(NetInstance value) {
    int ret = QtNetCoreQmlPINVOKE.NetInstanceVector_IndexOf(swigCPtr, NetInstance.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(NetInstance value) {
    int ret = QtNetCoreQmlPINVOKE.NetInstanceVector_LastIndexOf(swigCPtr, NetInstance.getCPtr(value));
    return ret;
  }

  public bool Remove(NetInstance value) {
    bool ret = QtNetCoreQmlPINVOKE.NetInstanceVector_Remove(swigCPtr, NetInstance.getCPtr(value));
    return ret;
  }

}

}
namespace Qt.NetCore {

public class NetTypeInfoCallbacks : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetTypeInfoCallbacks(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetTypeInfoCallbacks obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NetTypeInfoCallbacks() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_NetTypeInfoCallbacks(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool isValidType(string typeName) {
    bool ret = (SwigDerivedClassHasMethod("isValidType", swigMethodTypes0) ? QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_isValidTypeSwigExplicitNetTypeInfoCallbacks(swigCPtr, typeName) : QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_isValidType(swigCPtr, typeName));
    return ret;
  }

  public virtual void BuildTypeInfo(NetTypeInfo typeInfo) {
    if (SwigDerivedClassHasMethod("BuildTypeInfo", swigMethodTypes1)) QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_BuildTypeInfoSwigExplicitNetTypeInfoCallbacks(swigCPtr, NetTypeInfo.getCPtr(typeInfo)); else QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_BuildTypeInfo(swigCPtr, NetTypeInfo.getCPtr(typeInfo));
  }

  public virtual void CreateInstance(NetTypeInfo typeInfo, ref System.IntPtr instance) {
    if (SwigDerivedClassHasMethod("CreateInstance", swigMethodTypes2)) QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_CreateInstanceSwigExplicitNetTypeInfoCallbacks(swigCPtr, NetTypeInfo.getCPtr(typeInfo), ref instance); else QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_CreateInstance(swigCPtr, NetTypeInfo.getCPtr(typeInfo), ref instance);
  }

  public virtual void ReadProperty(NetPropertyInfo propertyInfo, NetInstance target, NetInstance result) {
    if (SwigDerivedClassHasMethod("ReadProperty", swigMethodTypes3)) QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_ReadPropertySwigExplicitNetTypeInfoCallbacks(swigCPtr, NetPropertyInfo.getCPtr(propertyInfo), NetInstance.getCPtr(target), NetInstance.getCPtr(result)); else QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_ReadProperty(swigCPtr, NetPropertyInfo.getCPtr(propertyInfo), NetInstance.getCPtr(target), NetInstance.getCPtr(result));
  }

  public virtual void WriteProperty(NetPropertyInfo propertyInfo, NetInstance target, NetInstance value) {
    if (SwigDerivedClassHasMethod("WriteProperty", swigMethodTypes4)) QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_WritePropertySwigExplicitNetTypeInfoCallbacks(swigCPtr, NetPropertyInfo.getCPtr(propertyInfo), NetInstance.getCPtr(target), NetInstance.getCPtr(value)); else QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_WriteProperty(swigCPtr, NetPropertyInfo.getCPtr(propertyInfo), NetInstance.getCPtr(target), NetInstance.getCPtr(value));
  }

  public virtual void InvokeMethod(NetMethodInfo methodInfo, NetInstance target, NetInstanceVector parameters, NetInstance result) {
    if (SwigDerivedClassHasMethod("InvokeMethod", swigMethodTypes5)) QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_InvokeMethodSwigExplicitNetTypeInfoCallbacks(swigCPtr, NetMethodInfo.getCPtr(methodInfo), NetInstance.getCPtr(target), NetInstanceVector.getCPtr(parameters), NetInstance.getCPtr(result)); else QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_InvokeMethod(swigCPtr, NetMethodInfo.getCPtr(methodInfo), NetInstance.getCPtr(target), NetInstanceVector.getCPtr(parameters), NetInstance.getCPtr(result));
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void ReleaseGCHandle(System.IntPtr gcHandle) {
    if (SwigDerivedClassHasMethod("ReleaseGCHandle", swigMethodTypes6)) QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_ReleaseGCHandleSwigExplicitNetTypeInfoCallbacks(swigCPtr, gcHandle); else QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_ReleaseGCHandle(swigCPtr, gcHandle);
  }

  public NetTypeInfoCallbacks() : this(QtNetCoreQmlPINVOKE.new_NetTypeInfoCallbacks(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("isValidType", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateNetTypeInfoCallbacks_0(SwigDirectorisValidType);
    if (SwigDerivedClassHasMethod("BuildTypeInfo", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateNetTypeInfoCallbacks_1(SwigDirectorBuildTypeInfo);
    if (SwigDerivedClassHasMethod("CreateInstance", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateNetTypeInfoCallbacks_2(SwigDirectorCreateInstance);
    if (SwigDerivedClassHasMethod("ReadProperty", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateNetTypeInfoCallbacks_3(SwigDirectorReadProperty);
    if (SwigDerivedClassHasMethod("WriteProperty", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateNetTypeInfoCallbacks_4(SwigDirectorWriteProperty);
    if (SwigDerivedClassHasMethod("InvokeMethod", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateNetTypeInfoCallbacks_5(SwigDirectorInvokeMethod);
    if (SwigDerivedClassHasMethod("ReleaseGCHandle", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateNetTypeInfoCallbacks_6(SwigDirectorReleaseGCHandle);
    QtNetCoreQmlPINVOKE.NetTypeInfoCallbacks_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(NetTypeInfoCallbacks));
    return hasDerivedMethod;
  }

  private bool SwigDirectorisValidType(string typeName) {
    return isValidType(typeName);
  }

  private void SwigDirectorBuildTypeInfo(global::System.IntPtr typeInfo) {
    BuildTypeInfo((typeInfo == global::System.IntPtr.Zero) ? null : new NetTypeInfo(typeInfo, false));
  }

  private void SwigDirectorCreateInstance(global::System.IntPtr typeInfo, ref System.IntPtr instance) {
    CreateInstance((typeInfo == global::System.IntPtr.Zero) ? null : new NetTypeInfo(typeInfo, false), ref instance);
  }

  private void SwigDirectorReadProperty(global::System.IntPtr propertyInfo, global::System.IntPtr target, global::System.IntPtr result) {
    ReadProperty((propertyInfo == global::System.IntPtr.Zero) ? null : new NetPropertyInfo(propertyInfo, false), (target == global::System.IntPtr.Zero) ? null : new NetInstance(target, false), (result == global::System.IntPtr.Zero) ? null : new NetInstance(result, false));
  }

  private void SwigDirectorWriteProperty(global::System.IntPtr propertyInfo, global::System.IntPtr target, global::System.IntPtr value) {
    WriteProperty((propertyInfo == global::System.IntPtr.Zero) ? null : new NetPropertyInfo(propertyInfo, false), (target == global::System.IntPtr.Zero) ? null : new NetInstance(target, false), (value == global::System.IntPtr.Zero) ? null : new NetInstance(value, false));
  }

  private void SwigDirectorInvokeMethod(global::System.IntPtr methodInfo, global::System.IntPtr target, global::System.IntPtr parameters, global::System.IntPtr result) {
    InvokeMethod((methodInfo == global::System.IntPtr.Zero) ? null : new NetMethodInfo(methodInfo, false), (target == global::System.IntPtr.Zero) ? null : new NetInstance(target, false), new NetInstanceVector(parameters, false), (result == global::System.IntPtr.Zero) ? null : new NetInstance(result, false));
  }

  private void SwigDirectorReleaseGCHandle(System.IntPtr gcHandle) {
    ReleaseGCHandle(gcHandle);
  }

  public delegate bool SwigDelegateNetTypeInfoCallbacks_0(string typeName);
  public delegate void SwigDelegateNetTypeInfoCallbacks_1(global::System.IntPtr typeInfo);
  public delegate void SwigDelegateNetTypeInfoCallbacks_2(global::System.IntPtr typeInfo, ref System.IntPtr instance);
  public delegate void SwigDelegateNetTypeInfoCallbacks_3(global::System.IntPtr propertyInfo, global::System.IntPtr target, global::System.IntPtr result);
  public delegate void SwigDelegateNetTypeInfoCallbacks_4(global::System.IntPtr propertyInfo, global::System.IntPtr target, global::System.IntPtr value);
  public delegate void SwigDelegateNetTypeInfoCallbacks_5(global::System.IntPtr methodInfo, global::System.IntPtr target, global::System.IntPtr parameters, global::System.IntPtr result);
  public delegate void SwigDelegateNetTypeInfoCallbacks_6(System.IntPtr gcHandle);

  private SwigDelegateNetTypeInfoCallbacks_0 swigDelegate0;
  private SwigDelegateNetTypeInfoCallbacks_1 swigDelegate1;
  private SwigDelegateNetTypeInfoCallbacks_2 swigDelegate2;
  private SwigDelegateNetTypeInfoCallbacks_3 swigDelegate3;
  private SwigDelegateNetTypeInfoCallbacks_4 swigDelegate4;
  private SwigDelegateNetTypeInfoCallbacks_5 swigDelegate5;
  private SwigDelegateNetTypeInfoCallbacks_6 swigDelegate6;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(string) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(NetTypeInfo) };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] { typeof(NetTypeInfo), typeof(System.IntPtr).MakeByRefType() };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] { typeof(NetPropertyInfo), typeof(NetInstance), typeof(NetInstance) };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] { typeof(NetPropertyInfo), typeof(NetInstance), typeof(NetInstance) };
  private static global::System.Type[] swigMethodTypes5 = new global::System.Type[] { typeof(NetMethodInfo), typeof(NetInstance), typeof(NetInstanceVector), typeof(NetInstance) };
  private static global::System.Type[] swigMethodTypes6 = new global::System.Type[] { typeof(System.IntPtr) };
}

}
namespace Qt.NetCore {

public class NetTypeInfoManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetTypeInfoManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetTypeInfoManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NetTypeInfoManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_NetTypeInfoManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static void setCallbacks(NetTypeInfoCallbacks callbacks) {
    QtNetCoreQmlPINVOKE.NetTypeInfoManager_setCallbacks(NetTypeInfoCallbacks.getCPtr(callbacks));
  }

  public static NetTypeInfo GetTypeInfo(string typeName) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetTypeInfoManager_GetTypeInfo(typeName);
    NetTypeInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetTypeInfo(cPtr, false);
    return ret;
  }

  public static NetInstance CreateInstance(NetTypeInfo typeInfo) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetTypeInfoManager_CreateInstance(NetTypeInfo.getCPtr(typeInfo));
    NetInstance ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetInstance(cPtr, false);
    return ret;
  }

  public static NetMethodInfo NewMethodInfo(NetTypeInfo parentTypeInfo, string methodName, NetTypeInfo returnType) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetTypeInfoManager_NewMethodInfo(NetTypeInfo.getCPtr(parentTypeInfo), methodName, NetTypeInfo.getCPtr(returnType));
    NetMethodInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetMethodInfo(cPtr, false);
    return ret;
  }

  public static NetPropertyInfo NewPropertyInfo(NetTypeInfo parentTypeInfo, string propertyName, NetTypeInfo returnType, bool canRead, bool canWrite) {
    global::System.IntPtr cPtr = QtNetCoreQmlPINVOKE.NetTypeInfoManager_NewPropertyInfo(NetTypeInfo.getCPtr(parentTypeInfo), propertyName, NetTypeInfo.getCPtr(returnType), canRead, canWrite);
    NetPropertyInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetPropertyInfo(cPtr, false);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public NetTypeInfoManager() : this(QtNetCoreQmlPINVOKE.new_NetTypeInfoManager(), true) {
  }

}

}
namespace Qt.NetCore {

public enum ApplicationAttribute {
  AA_ImmediateWidgetCreation = 0,
  AA_MSWindowsUseDirect3DByDefault = 1,
  AA_DontShowIconsInMenus = 2,
  AA_NativeWindows = 3,
  AA_DontCreateNativeWidgetSiblings = 4,
  AA_PluginApplication = 5,
  AA_MacPluginApplication = AA_PluginApplication,
  AA_DontUseNativeMenuBar = 6,
  AA_MacDontSwapCtrlAndMeta = 7,
  AA_Use96Dpi = 8,
  AA_X11InitThreads = 10,
  AA_SynthesizeTouchForUnhandledMouseEvents = 11,
  AA_SynthesizeMouseForUnhandledTouchEvents = 12,
  AA_UseHighDpiPixmaps = 13,
  AA_ForceRasterWidgets = 14,
  AA_UseDesktopOpenGL = 15,
  AA_UseOpenGLES = 16,
  AA_UseSoftwareOpenGL = 17,
  AA_ShareOpenGLContexts = 18,
  AA_SetPalette = 19,
  AA_EnableHighDpiScaling = 20,
  AA_DisableHighDpiScaling = 21,
  AA_UseStyleSheetPropagationInWidgetStyles = 22,
  AA_DontUseNativeDialogs = 23,
  AA_SynthesizeMouseForUnhandledTabletEvents = 24,
  AA_CompressHighFrequencyEvents = 25,
  AA_DontCheckOpenGLContextThreadAffinity = 26,
  AA_AttributeCount
}

}
namespace Qt.NetCore {

public class QCoreApplication : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal QCoreApplication(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(QCoreApplication obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~QCoreApplication() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_QCoreApplication(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static void setAttribute(ApplicationAttribute attribute, bool on) {
    QtNetCoreQmlPINVOKE.QCoreApplication_setAttribute__SWIG_0((int)attribute, on);
  }

  public static void setAttribute(ApplicationAttribute attribute) {
    QtNetCoreQmlPINVOKE.QCoreApplication_setAttribute__SWIG_1((int)attribute);
  }

  public int exec() {
    int ret = QtNetCoreQmlPINVOKE.QCoreApplication_exec(swigCPtr);
    return ret;
  }

}

}
namespace Qt.NetCore {

public class QGuiApplication : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal QGuiApplication(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(QGuiApplication obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~QGuiApplication() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_QGuiApplication(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public QGuiApplication(StringVector argv) : this(QtNetCoreQmlPINVOKE.new_QGuiApplication(StringVector.getCPtr(argv)), true) {
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public int exec() {
    int ret = QtNetCoreQmlPINVOKE.QGuiApplication_exec(swigCPtr);
    return ret;
  }

}

}
namespace Qt.NetCore {

public class QQmlApplicationEngine : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal QQmlApplicationEngine(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(QQmlApplicationEngine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~QQmlApplicationEngine() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QtNetCoreQmlPINVOKE.delete_QQmlApplicationEngine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public void loadFile(string filePath) {
    QtNetCoreQmlPINVOKE.QQmlApplicationEngine_loadFile(swigCPtr, filePath);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
  }

  public QQmlApplicationEngine() : this(QtNetCoreQmlPINVOKE.new_QQmlApplicationEngine(), true) {
  }

}

}
namespace Qt.NetCore {

class QtNetCoreQmlPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="SWIGRegisterExceptionCallbacks_QtNetCoreQml")]
    public static extern void SWIGRegisterExceptionCallbacks_QtNetCoreQml(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_QtNetCoreQml")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_QtNetCoreQml(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_QtNetCoreQml(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_QtNetCoreQml(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(QtNetCoreQmlPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(QtNetCoreQmlPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="SWIGRegisterStringCallback_QtNetCoreQml")]
    public static extern void SWIGRegisterStringCallback_QtNetCoreQml(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_QtNetCoreQml(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static QtNetCoreQmlPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_Clear")]
  public static extern void StringVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_Add")]
  public static extern void StringVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_size")]
  public static extern uint StringVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_capacity")]
  public static extern uint StringVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_reserve")]
  public static extern void StringVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_StringVector__SWIG_0")]
  public static extern global::System.IntPtr new_StringVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_StringVector__SWIG_1")]
  public static extern global::System.IntPtr new_StringVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_StringVector__SWIG_2")]
  public static extern global::System.IntPtr new_StringVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_getitemcopy")]
  public static extern string StringVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_getitem")]
  public static extern string StringVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_setitem")]
  public static extern void StringVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_AddRange")]
  public static extern void StringVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_GetRange")]
  public static extern global::System.IntPtr StringVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_Insert")]
  public static extern void StringVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_InsertRange")]
  public static extern void StringVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_RemoveAt")]
  public static extern void StringVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_RemoveRange")]
  public static extern void StringVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_Repeat")]
  public static extern global::System.IntPtr StringVector_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_Reverse__SWIG_0")]
  public static extern void StringVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_Reverse__SWIG_1")]
  public static extern void StringVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_SetRange")]
  public static extern void StringVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_Contains")]
  public static extern bool StringVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_IndexOf")]
  public static extern int StringVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_LastIndexOf")]
  public static extern int StringVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_StringVector_Remove")]
  public static extern bool StringVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_StringVector")]
  public static extern void delete_StringVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_NetInstance")]
  public static extern global::System.IntPtr new_NetInstance(System.IntPtr jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstance_GetGCHandle")]
  public static extern System.IntPtr NetInstance_GetGCHandle(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstance_GetTypeInfo")]
  public static extern global::System.IntPtr NetInstance_GetTypeInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_NetInstance")]
  public static extern void delete_NetInstance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_NetVariant")]
  public static extern global::System.IntPtr new_NetVariant();

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetVariant_GetVariantType")]
  public static extern int NetVariant_GetVariantType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetVariant_SetNetInstance")]
  public static extern void NetVariant_SetNetInstance(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetVariant_GetNetInstance")]
  public static extern global::System.IntPtr NetVariant_GetNetInstance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetVariant_SetBool")]
  public static extern void NetVariant_SetBool(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetVariant_GetBool")]
  public static extern bool NetVariant_GetBool(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetVariant_SetInt")]
  public static extern void NetVariant_SetInt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetVariant_GetInt")]
  public static extern int NetVariant_GetInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_NetVariant")]
  public static extern void delete_NetVariant(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_NetTypeInfo")]
  public static extern global::System.IntPtr new_NetTypeInfo(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_NetTypeInfo")]
  public static extern void delete_NetTypeInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfo_GetTypeName")]
  public static extern string NetTypeInfo_GetTypeName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfo_AddMethod")]
  public static extern void NetTypeInfo_AddMethod(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfo_GetMethodCount")]
  public static extern int NetTypeInfo_GetMethodCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfo_GetMethod")]
  public static extern global::System.IntPtr NetTypeInfo_GetMethod(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfo_AddProperty")]
  public static extern void NetTypeInfo_AddProperty(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfo_GetPropertyCount")]
  public static extern int NetTypeInfo_GetPropertyCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfo_GetProperty")]
  public static extern global::System.IntPtr NetTypeInfo_GetProperty(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_NetMethodInfo")]
  public static extern global::System.IntPtr new_NetMethodInfo(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetMethodInfo_GetMethodName")]
  public static extern string NetMethodInfo_GetMethodName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetMethodInfo_GetReturnType")]
  public static extern global::System.IntPtr NetMethodInfo_GetReturnType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetMethodInfo_AddParameter")]
  public static extern void NetMethodInfo_AddParameter(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetMethodInfo_GetParameterCount")]
  public static extern int NetMethodInfo_GetParameterCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetMethodInfo_GetParameterInfo")]
  public static extern void NetMethodInfo_GetParameterInfo(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_NetMethodInfo")]
  public static extern void delete_NetMethodInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_NetPropertyInfo")]
  public static extern global::System.IntPtr new_NetPropertyInfo(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, bool jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetPropertyInfo_GetParentType")]
  public static extern global::System.IntPtr NetPropertyInfo_GetParentType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetPropertyInfo_GetPropertyName")]
  public static extern string NetPropertyInfo_GetPropertyName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetPropertyInfo_GetReturnType")]
  public static extern global::System.IntPtr NetPropertyInfo_GetReturnType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetPropertyInfo_CanRead")]
  public static extern bool NetPropertyInfo_CanRead(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetPropertyInfo_CanWrite")]
  public static extern bool NetPropertyInfo_CanWrite(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_NetPropertyInfo")]
  public static extern void delete_NetPropertyInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_Clear")]
  public static extern void NetInstanceVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_Add")]
  public static extern void NetInstanceVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_size")]
  public static extern uint NetInstanceVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_capacity")]
  public static extern uint NetInstanceVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_reserve")]
  public static extern void NetInstanceVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_NetInstanceVector__SWIG_0")]
  public static extern global::System.IntPtr new_NetInstanceVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_NetInstanceVector__SWIG_1")]
  public static extern global::System.IntPtr new_NetInstanceVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_NetInstanceVector__SWIG_2")]
  public static extern global::System.IntPtr new_NetInstanceVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_getitemcopy")]
  public static extern global::System.IntPtr NetInstanceVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_getitem")]
  public static extern global::System.IntPtr NetInstanceVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_setitem")]
  public static extern void NetInstanceVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_AddRange")]
  public static extern void NetInstanceVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_GetRange")]
  public static extern global::System.IntPtr NetInstanceVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_Insert")]
  public static extern void NetInstanceVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_InsertRange")]
  public static extern void NetInstanceVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_RemoveAt")]
  public static extern void NetInstanceVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_RemoveRange")]
  public static extern void NetInstanceVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_Repeat")]
  public static extern global::System.IntPtr NetInstanceVector_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_Reverse__SWIG_0")]
  public static extern void NetInstanceVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_Reverse__SWIG_1")]
  public static extern void NetInstanceVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_SetRange")]
  public static extern void NetInstanceVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_Contains")]
  public static extern bool NetInstanceVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_IndexOf")]
  public static extern int NetInstanceVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_LastIndexOf")]
  public static extern int NetInstanceVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetInstanceVector_Remove")]
  public static extern bool NetInstanceVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_NetInstanceVector")]
  public static extern void delete_NetInstanceVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_NetTypeInfoCallbacks")]
  public static extern void delete_NetTypeInfoCallbacks(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_isValidType")]
  public static extern bool NetTypeInfoCallbacks_isValidType(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_isValidTypeSwigExplicitNetTypeInfoCallbacks")]
  public static extern bool NetTypeInfoCallbacks_isValidTypeSwigExplicitNetTypeInfoCallbacks(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_BuildTypeInfo")]
  public static extern void NetTypeInfoCallbacks_BuildTypeInfo(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_BuildTypeInfoSwigExplicitNetTypeInfoCallbacks")]
  public static extern void NetTypeInfoCallbacks_BuildTypeInfoSwigExplicitNetTypeInfoCallbacks(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_CreateInstance")]
  public static extern void NetTypeInfoCallbacks_CreateInstance(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, ref System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_CreateInstanceSwigExplicitNetTypeInfoCallbacks")]
  public static extern void NetTypeInfoCallbacks_CreateInstanceSwigExplicitNetTypeInfoCallbacks(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, ref System.IntPtr jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_ReadProperty")]
  public static extern void NetTypeInfoCallbacks_ReadProperty(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_ReadPropertySwigExplicitNetTypeInfoCallbacks")]
  public static extern void NetTypeInfoCallbacks_ReadPropertySwigExplicitNetTypeInfoCallbacks(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_WriteProperty")]
  public static extern void NetTypeInfoCallbacks_WriteProperty(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_WritePropertySwigExplicitNetTypeInfoCallbacks")]
  public static extern void NetTypeInfoCallbacks_WritePropertySwigExplicitNetTypeInfoCallbacks(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_InvokeMethod")]
  public static extern void NetTypeInfoCallbacks_InvokeMethod(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_InvokeMethodSwigExplicitNetTypeInfoCallbacks")]
  public static extern void NetTypeInfoCallbacks_InvokeMethodSwigExplicitNetTypeInfoCallbacks(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_ReleaseGCHandle")]
  public static extern void NetTypeInfoCallbacks_ReleaseGCHandle(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_ReleaseGCHandleSwigExplicitNetTypeInfoCallbacks")]
  public static extern void NetTypeInfoCallbacks_ReleaseGCHandleSwigExplicitNetTypeInfoCallbacks(global::System.Runtime.InteropServices.HandleRef jarg1, System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_NetTypeInfoCallbacks")]
  public static extern global::System.IntPtr new_NetTypeInfoCallbacks();

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoCallbacks_director_connect")]
  public static extern void NetTypeInfoCallbacks_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, NetTypeInfoCallbacks.SwigDelegateNetTypeInfoCallbacks_0 delegate0, NetTypeInfoCallbacks.SwigDelegateNetTypeInfoCallbacks_1 delegate1, NetTypeInfoCallbacks.SwigDelegateNetTypeInfoCallbacks_2 delegate2, NetTypeInfoCallbacks.SwigDelegateNetTypeInfoCallbacks_3 delegate3, NetTypeInfoCallbacks.SwigDelegateNetTypeInfoCallbacks_4 delegate4, NetTypeInfoCallbacks.SwigDelegateNetTypeInfoCallbacks_5 delegate5, NetTypeInfoCallbacks.SwigDelegateNetTypeInfoCallbacks_6 delegate6);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoManager_setCallbacks")]
  public static extern void NetTypeInfoManager_setCallbacks(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoManager_GetTypeInfo")]
  public static extern global::System.IntPtr NetTypeInfoManager_GetTypeInfo(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoManager_CreateInstance")]
  public static extern global::System.IntPtr NetTypeInfoManager_CreateInstance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoManager_NewMethodInfo")]
  public static extern global::System.IntPtr NetTypeInfoManager_NewMethodInfo(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_NetTypeInfoManager_NewPropertyInfo")]
  public static extern global::System.IntPtr NetTypeInfoManager_NewPropertyInfo(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, bool jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_NetTypeInfoManager")]
  public static extern global::System.IntPtr new_NetTypeInfoManager();

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_NetTypeInfoManager")]
  public static extern void delete_NetTypeInfoManager(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_QCoreApplication_setAttribute__SWIG_0")]
  public static extern void QCoreApplication_setAttribute__SWIG_0(int jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_QCoreApplication_setAttribute__SWIG_1")]
  public static extern void QCoreApplication_setAttribute__SWIG_1(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_QCoreApplication_exec")]
  public static extern int QCoreApplication_exec(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_QCoreApplication")]
  public static extern void delete_QCoreApplication(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_QGuiApplication")]
  public static extern global::System.IntPtr new_QGuiApplication(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_QGuiApplication_exec")]
  public static extern int QGuiApplication_exec(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_QGuiApplication")]
  public static extern void delete_QGuiApplication(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_QQmlApplicationEngine_loadFile")]
  public static extern void QQmlApplicationEngine_loadFile(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_new_QQmlApplicationEngine")]
  public static extern global::System.IntPtr new_QQmlApplicationEngine();

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_delete_QQmlApplicationEngine")]
  public static extern void delete_QQmlApplicationEngine(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("QtNetCoreQml", EntryPoint="CSharp_registerNetType")]
  public static extern int registerNetType(string jarg1, string jarg2, int jarg3, int jarg4, string jarg5);
}

}
namespace Qt.NetCore {

public class QtNetCoreQml {
  public static int registerNetType(string netType, string uri, int versionMajor, int versionMinor, string qmlName) {
    int ret = QtNetCoreQmlPINVOKE.registerNetType(netType, uri, versionMajor, versionMinor, qmlName);
    if (QtNetCoreQmlPINVOKE.SWIGPendingException.Pending) throw QtNetCoreQmlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
namespace Qt.NetCore {

public class SWIGTYPE_p_p_NetTypeInfo {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal SWIGTYPE_p_p_NetTypeInfo(global::System.IntPtr cPtr, bool futureUse) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  protected SWIGTYPE_p_p_NetTypeInfo() {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SWIGTYPE_p_p_NetTypeInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }
}

}
namespace Qt.NetCore {

public class SWIGTYPE_p_std__string {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal SWIGTYPE_p_std__string(global::System.IntPtr cPtr, bool futureUse) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  protected SWIGTYPE_p_std__string() {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SWIGTYPE_p_std__string obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }
}

}
